---
name: Build and deploy

on:
  push:
    branches:
      - main
    tags:
      - "v*.*"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build CVs
        run: |
          make

      - name: Upload CVs artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cv-pdfs
          path: |
            outputs/english_cv.pdf
            outputs/french_cv.pdf
          retention-days: 7

  create-preview:
    needs: build
    runs-on: ubuntu-24.04
    container:
      image: dpokidov/imagemagick:7.1.1-38-bookworm

    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download CVs artifacts
        uses: actions/download-artifact@v4
        with:
          name: cv-pdfs
          path: outputs

      - name: Create PNG preview
        run: |
          convert -density 150 -background white -alpha remove -quality 90 outputs/english_cv.pdf[0] outputs/english_cv_preview.png
          convert -density 150 -background white -alpha remove -quality 90 outputs/french_cv.pdf[0] outputs/french_cv_preview.png

      - name: Upload Preview artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cv-preview
          path: |
            outputs/english_cv_preview.png
            outputs/french_cv_preview.png
          retention-days: 7

  deploy:
    needs: [build, create-preview]
    runs-on: ubuntu-24.04

    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            outputs/english_cv.pdf
            outputs/french_cv.pdf
            outputs/english_cv_preview.png
            outputs/french_cv_preview.png
          fail_on_unmatched_files: true
